[pytest]

python_files = test_*.py
python_functions = test_*
addopts = -vv -s -p no:cacheprovider

markers =
    smoke: быстрая проверка основных функций
    regression: полная проверка функционала
    btc: проверка тестов для биткоина
    eth: проверка тестов для эфира