# utils/btc_response.py
BTC_RESPONSE = {
    'ext_code': '',
    'ext_info': {},
    'result': {'count': 53,
                'items': [{'accountId': '36520269',
                           'authStatus': 1,
                           'authTag': ['VA1', 'GA', 'VA'],
                           'ban': False,
                           'baned': False,
                           'blocked': 'N',
                           'createDate': '1754768433000',
                           'currencyId': 'RUB',
                           'executedQuantity': '0.01220562',
                           'fee': '',
                           'finishNum': 134,
                           'frozenQuantity': '0',
                           'id': '1954266564794441728',
                           'isOnline': False,
                           'itemType': 'ORIGIN',
                           'lastLogoutTime': '1755341342',
                           'lastQuantity': '0.01185786',
                           'makerContact': True,
                           'maxAmount': '114902.66',
                           'minAmount': '20000.00',
                           'nickName': 'Suleyman____66',
                           'orderNum': 134,
                           'paymentPeriod': 30,
                           'payments': ['64', '382'],
                           'premium': '0',
                           'price': '9690000.00',
                           'priceType': 0,
                           'quantity': '0.02406348',
                           'recentExecuteRate': 93,
                           'recentOrderNum': 422,
                           'recommend': False,
                           'recommendTag': '',
                           'remark': 'Проверенный МЕРЧАНТ.Только 1 лица или '
                                    'родственники ',
                           'side': 1,
                           'status': 10,
                           'symbolInfo': {'buyAd': None,
                                          'buyFeeRate': '',
                                          'currency': {'currencyId': 'RUB',
                                                       'exchangeId': '0',
                                                       'id': '7',
                                                       'orgId': '9001',
                                                       'scale': 2},
                                          'currencyId': 'RUB',
                                          'currencyLowerMaxQuote': '500',
                                          'currencyMaxQuote': '2000000',
                                          'currencyMinQuote': '500',
                                          'exchangeId': '301',
                                          'id': '31',
                                          'itemDownRange': '80',
                                          'itemSideLimit': 3,
                                          'itemUpRange': '120',
                                          'k$1=<SECRET_API_KEY>': '0',
                                          'lowerLimitAlarm': 90,
                                          'orderAutoCancelMinute': 15,
                                          'orderFinishMinute': 10,
                                          'orgId': '9001',
                                          'sellAd': None,
                                          'sellFeeRate': '',
                                          'status': 1,
                                          'token': {'exchangeId': '0',
                                                    'id': '2',
                                                    'orgId': '9001',
                                                    'scale': 8,
                                                    'sequence': 0,
                                                    'tokenId': 'BTC'},
                                          'tokenId': 'BTC',
                                          'tokenMaxQuote': '2',
                                          'tokenMinQuote': '0.00005',
                                          'tradeSide': 9,
                                          'upperLimitAlarm': 110},
                           'tokenId': 'BTC',
                           'tokenName': '',
                           'tradingPreferenceSet': {'completeRateDay30': '',
                                                    'hasCompleteRateDay30': 0,
                                                    'hasNationalLimit': 0,
                                                    'hasOrderFinishNumberDay30': 0,
                                                    'hasRegisterTime': 0,
                                                    'hasSingleUserOrderLimit': 0,
                                                    'hasUnPostAd': 0,
                                                    'isEmail': 0,
                                                    'isKyc': 1,
                                                    'isMobile': 0,
                                                    'nationalLimit': '',
                                                    'orderFinishNumberDay30': 0,
                                                    'registerTimeThreshold': 0,
                                                    'singleUserOrderLimit': 0},
                           'userId': '36520267',
                           'userMaskId': 's9b9a142114b244d3bc629540ee42a9ac',
                           'userType': 'PERSONAL',
                           'verificationOrderAmount': '0',
                           'verificationOrderLabels': [],
                           'verificationOrderSwitch': False,
                           'version': 0},
                          {'accountId': '124998661',
                           'authStatus': 1,
                           'authTag': ['VA1', 'BA', 'GA', 'VA', 'VA2', 'VA3'],
                           'ban': False,
                           'baned': False,
                           'blocked': 'N',
                           'createDate': '1754292375000',
                           'currencyId': 'RUB',
                           'executedQuantity': '0',
                           'fee': '',
                           'finishNum': 6,
                           'frozenQuantity': '0.01587418',
                           'id': '1952269833250889728',
                           'isOnline': True,
                           'itemType': 'ORIGIN',
                           'lastLogoutTime': '1753299169',
                           'lastQuantity': '0.01122582',
                           'makerContact': False,
                           'maxAmount': '109612.15',
                           'minAmount': '50000.00',
                           'nickName': 'OnlyFinance',
                           'orderNum': 7,
                           'paymentPeriod': 30,
                           'payments': ['64', '382'],
                           'premium': '0',
                           'price': '9764289.59',
                           'priceType': 0,
                           'quantity': '0.0271',
                           'recentExecuteRate': 100,
                           'recentOrderNum': 1794,
                           'recommend': False,
                           'recommendTag': '',
                           'remark': 'Здравствуйте! Принимаю оплату по номеру '
                                    'телефона . Принимаю перевод ТОЛЬКО ОТ 1-го '
                                    'ЛИЦА Отпускаю быстро  Всегда PDF - '
                                    'чек после оплаты  (БЕЗ PDF НЕ ОТПУСКАЮ '
                                    'USDT)Принимаю на карту доверенного '
                                    'лица Могу запросить дополнительные '
                                    'подтверждения Работаю в порядке очереди. '
                                    'Онлайн 24/7 Открыт к постоянному '
                                    'сотрудничеству, контакты в чате сделки',
                           'side': 1,
                           'status': 10,
                           'symbolInfo': {'buyAd': None,
                                          'buyFeeRate': '',
                                          'currency': {'currencyId': 'RUB',
                                                       'exchangeId': '0',
                                                       'id': '7',
                                                       'orgId': '9001',
                                                       'scale': 2},
                                          'currencyId': 'RUB',
                                          'currencyLowerMaxQuote': '500',
                                          'currencyMaxQuote': '2000000',
                                          'currencyMinQuote': '500',
                                          'exchangeId': '301',
                                          'id': '31',
                                          'itemDownRange': '80',
                                          'itemSideLimit': 3,
                                          'itemUpRange': '120',
                                          'k$1=<SECRET_API_KEY>': '0',
                                          'lowerLimitAlarm': 90,
                                          'orderAutoCancelMinute': 15,
                                          'orderFinishMinute': 10,
                                          'orgId': '9001',
                                          'sellAd': None,
                                          'sellFeeRate': '',
                                          'status': 1,
                                          'token': {'exchangeId': '0',
                                                    'id': '2',
                                                    'orgId': '9001',
                                                    'scale': 8,
                                                    'sequence': 0,
                                                    'tokenId': 'BTC'},
                                          'tokenId': 'BTC',
                                          'tokenMaxQuote': '2',
                                          'tokenMinQuote': '0.00005',
                                          'tradeSide': 9,
                                          'upperLimitAlarm': 110},
                           'tokenId': 'BTC',
                           'tokenName': '',
                           'tradingPreferenceSet': {'completeRateDay30': '',
                                                    'hasCompleteRateDay30': 0,
                                                    'hasNationalLimit': 0,
                                                    'hasOrderFinishNumberDay30': 0,
                                                    'hasRegisterTime': 0,
                                                    'hasSingleUserOrderLimit': 0,
                                                    'hasUnPostAd': 0,
                                                    'isEmail': 0,
                                                    'isKyc': 1,
                                                    'isMobile': 0,
                                                    'nationalLimit': '',
                                                    'orderFinishNumberDay30': 0,
                                                    'registerTimeThreshold': 0,
                                                    'singleUserOrderLimit': 0},
                           'userId': '124998659',
                           'userMaskId': 'sbc3e7b6c1e724a4b9b74c9b499042904',
                           'userType': 'PERSONAL',
                           'verificationOrderAmount': '0',
                           'verificationOrderLabels': [],
                           'verificationOrderSwitch': False,
                           'version': 0},
                          {'accountId': '22223716',
                           'authStatus': 1,
                           'authTag': ['VA1', 'GA', 'VA'],
                           'ban': False,
                           'baned': False,
                           'blocked': 'N',
                           'createDate': '1755341951000',
                           'currencyId': 'RUB',
                           'executedQuantity': '0',
                           'fee': '',
                           'finishNum': 0,
                           'frozenQuantity': '0',
                           'id': '1956672076467290112',
                           'isOnline': False,
                           'itemType': 'ORIGIN',
                           'lastLogoutTime': '1755341994',
                           'lastQuantity': '0.00087',
                           'makerContact': True,
                           'maxAmount': '8500.00',
                           'minAmount': '8500.00',
                           'nickName': 'alex pay',
                           'orderNum': 0,
                           'paymentPeriod': 15,
                           'payments': ['64', '382'],
                           'premium': '0',
                           'price': '9771000.00',
                           'priceType': 0,
                           'quantity': '0.00087',
                           'recentExecuteRate': 100,
                           'recentOrderNum': 381,
                           'recommend': False,
                           'recommendTag': '',
                           'remark': 'по сбп на Ингосстрах банк (принимаю со всех '
                                    'банк) ',
                           'side': 1,
                           'status': 10,
                           'symbolInfo': {'buyAd': None,
                                          'buyFeeRate': '',
                                          'currency': {'currencyId': 'RUB',
                                                       'exchangeId': '0',
                                                       'id': '7',
                                                       'orgId': '9001',
                                                       'scale': 2},
                                          'currencyId': 'RUB',
                                          'currencyLowerMaxQuote': '500',
                                          'currencyMaxQuote': '2000000',
                                          'currencyMinQuote': '500',
                                          'exchangeId': '301',
                                          'id': '31',
                                          'itemDownRange': '80',
                                          'itemSideLimit': 3,
                                          'itemUpRange': '120',
                                          'k$1=<SECRET_API_KEY>': '0',
                                          'lowerLimitAlarm': 90,
                                          'orderAutoCancelMinute': 15,
                                          'orderFinishMinute': 10,
                                          'orgId': '9001',
                                          'sellAd': None,
                                          'sellFeeRate': '',
                                          'status': 1,
                                          'token': {'exchangeId': '0',
                                                    'id': '2',
                                                    'orgId': '9001',
                                                    'scale': 8,
                                                    'sequence': 0,
                                                    'tokenId': 'BTC'},
                                          'tokenId': 'BTC',
                                          'tokenMaxQuote': '2',
                                          'tokenMinQuote': '0.00005',
                                          'tradeSide': 9,
                                          'upperLimitAlarm': 110},
                           'tokenId': 'BTC',
                           'tokenName': '',
                           'tradingPreferenceSet': {'completeRateDay30': '',
                                                    'hasCompleteRateDay30': 0,
                                                    'hasNationalLimit': 0,
                                                    'hasOrderFinishNumberDay30': 0,
                                                    'hasRegisterTime': 0,
                                                    'hasSingleUserOrderLimit': 0,
                                                    'hasUnPostAd': 0,
                                                    'isEmail': 0,
                                                    'isKyc': 1,
                                                    'isMobile': 0,
                                                    'nationalLimit': '',
                                                    'orderFinishNumberDay30': 0,
                                                    'registerTimeThreshold': 0,
                                                    'singleUserOrderLimit': 0},
                           'userId': '22223714',
                           'userMaskId': 's0af8093b9474411faac805312ab0f84c',
                           'userType': 'PERSONAL',
                           'verificationOrderAmount': '0',
                           'verificationOrderLabels': [],
                           'verificationOrderSwitch': False,
                           'version': 0},
                          {'accountId': '65484805',
                           'authStatus': 1,
                           'authTag': ['VA1', 'GA', 'VA', 'VA2', 'VA3'],
                           'ban': False,
                           'baned': False,
                           'blocked': 'N',
                           'createDate': '1747219181000',
                           'currencyId': 'RUB',
                           'executedQuantity': '0',
                           'fee': '',
                           'finishNum': 668,
                           'frozenQuantity': '0',
                           'id': '1922602708103450624',
                           'isOnline': True,
                           'itemType': 'ORIGIN',
                           'lastLogoutTime': '1755341006',
                           'lastQuantity': '0.00455779',
                           'makerContact': True,
                           'maxAmount': '44568.36',
                           'minAmount': '20000.00',
                           'nickName': 'monty.mcqueen',
                           'orderNum': 673,
                           'paymentPeriod': 30,
                           'payments': ['64', '382'],
                           'premium': '103.95',
                           'price': '9778504.26',
                           'priceType': 1,
                           'quantity': '0.00455779',
                           'recentExecuteRate': 98,
                           'recentOrderNum': 1648,
                           'recommend': False,
                           'recommendTag': '',
                           'remark': 'Помогу новичкам разобраться!\n'
                                    'Принимаю от 1-Х лиц, от 3-Х лиц только с '
                                    'ФОТО на фоне сделки \n'
                                    'Работаю по СБП, по номеру телефона, с '
                                    'любыми банками \n'
                                    'Работаю в порядке очереди ',
                           'side': 1,
                           'status': 10,
                           'symbolInfo': {'buyAd': None,
                                          'buyFeeRate': '',
                                          'currency': {'currencyId': 'RUB',
                                                       'exchangeId': '0',
                                                       'id': '7',
                                                       'orgId': '9001',
                                                       'scale': 2},
                                          'currencyId': 'RUB',
                                          'currencyLowerMaxQuote': '500',
                                          'currencyMaxQuote': '2000000',
                                          'currencyMinQuote': '500',
                                          'exchangeId': '301',
                                          'id': '31',
                                          'itemDownRange': '80',
                                          'itemSideLimit': 3,
                                          'itemUpRange': '120',
                                          'k$1=<SECRET_API_KEY>': '0',
                                          'lowerLimitAlarm': 90,
                                          'orderAutoCancelMinute': 15,
                                          'orderFinishMinute': 10,
                                          'orgId': '9001',
                                          'sellAd': None,
                                          'sellFeeRate': '',
                                          'status': 1,
                                          'token': {'exchangeId': '0',
                                                    'id': '2',
                                                    'orgId': '9001',
                                                    'scale': 8,
                                                    'sequence': 0,
                                                    'tokenId': 'BTC'},
                                          'tokenId': 'BTC',
                                          'tokenMaxQuote': '2',
                                          'tokenMinQuote': '0.00005',
                                          'tradeSide': 9,
                                          'upperLimitAlarm': 110},
                           'tokenId': 'BTC',
                           'tokenName': '',
                           'tradingPreferenceSet': {'completeRateDay30': '',
                                                    'hasCompleteRateDay30': 0,
                                                    'hasNationalLimit': 0,
                                                    'hasOrderFinishNumberDay30': 0,
                                                    'hasRegisterTime': 0,
                                                    'hasSingleUserOrderLimit': 0,
                                                    'hasUnPostAd': 0,
                                                    'isEmail': 0,
                                                    'isKyc': 1,
                                                    'isMobile': 0,
                                                    'nationalLimit': '',
                                                    'orderFinishNumberDay30': 0,
                                                    'registerTimeThreshold': 0,
                                                    'singleUserOrderLimit': 0},
                           'userId': '65484804',
                           'userMaskId': 'se9442e769a3543698a2c38665d9760ed',
                           'userType': 'PERSONAL',
                           'verificationOrderAmount': '0',
                           'verificationOrderLabels': [],
                           'verificationOrderSwitch': False,
                           'version': 0},
                          {'accountId': '102420999',
                           'authStatus': 1,
                           'authTag': ['VA1', 'BA', 'GA', 'VA'],
                           'ban': False,
                           'baned': False,
                           'blocked': 'N',
                           'createDate': '1745596875000',
                           'currencyId': 'RUB',
                           'executedQuantity': '0.02773003',
                           'fee': '',
                           'finishNum': 146,
                           'frozenQuantity': '0',
                           'id': '1915798262128443392',
                           'isOnline': False,
                           'itemType': 'ORIGIN',
                           'lastLogoutTime': '1755341666',
                           'lastQuantity': '0.03227376',
                           'makerContact': True,
                           'maxAmount': '315637.37',
                           'minAmount': '30000.00',
                           'nickName': 'N1one',
                           'orderNum': 147,
                           'paymentPeriod': 30,
                           'payments': ['581', '582', '382'],
                           'premium': '0',
                           'price': '9780000.00',
                           'priceType': 0,
                           'quantity': '0.06000379',
                           'recentExecuteRate': 97,
                           'recentOrderNum': 1015,
                           'recommend': False,
                           'recommendTag': '',
                           'remark': 'Быстрый и безопасный обмен \n'
                                    'От 3-его лица могу запросить квитанцию об '
                                    'оплате в PDF \n'
                                    '\u200dОплата на карту доверенного лица '
                                    ' \n'
                                    'В связи с участившимися сбоями работы '
                                    'банка и случаями мошенничества   Могу '
                                    'запрость доп. верификацию. \n'
                                    'Лучшие условия для постоянных клиентов   \n'
                                    '\n'
                                    '                                                                    '
                                    'ВНИМАНИЕ  \n'
                                    'ВСЕ МОШЕННИКИ/ХУДОЖНИКИ МИМО, У НАС ЕСТЬ '
                                    'СОФТ, КОТОРЫЙ ОПРЕДЕЛЯЕТ ОТРИСОВАННЫЕ ЧЕКИ - '
                                    'МОМЕНТАЛЬНАЯ АППЕЛЛЯЦИЯ И ЖАЛОБА',
                           'side': 1,
                           'status': 10,
                           'symbolInfo': {'buyAd': None,
                                          'buyFeeRate': '',
                                          'currency': {'currencyId': 'RUB',
                                                       'exchangeId': '0',
                                                       'id': '7',
                                                       'orgId': '9001',
                                                       'scale': 2},
                                          'currencyId': 'RUB',
                                          'currencyLowerMaxQuote': '500',
                                          'currencyMaxQuote': '2000000',
                                          'currencyMinQuote': '500',
                                          'exchangeId': '301',
                                          'id': '31',
                                          'itemDownRange': '80',
                                          'itemSideLimit': 3,
                                          'itemUpRange': '120',
                                          'k$1=<SECRET_API_KEY>': '0',
                                          'lowerLimitAlarm': 90,
                                          'orderAutoCancelMinute': 15,
                                          'orderFinishMinute': 10,
                                          'orgId': '9001',
                                          'sellAd': None,
                                          'sellFeeRate': '',
                                          'status': 1,
                                          'token': {'exchangeId': '0',
                                                    'id': '2',
                                                    'orgId': '9001',
                                                    'scale': 8,
                                                    'sequence': 0,
                                                    'tokenId': 'BTC'},
                                          'tokenId': 'BTC',
                                          'tokenMaxQuote': '2',
                                          'tokenMinQuote': '0.00005',
                                          'tradeSide': 9,
                                          'upperLimitAlarm': 110},
                           'tokenId': 'BTC',
                           'tokenName': '',
                           'tradingPreferenceSet': {'completeRateDay30': '',
                                                    'hasCompleteRateDay30': 0,
                                                    'hasNationalLimit': 0,
                                                    'hasOrderFinishNumberDay30': 0,
                                                    'hasRegisterTime': 0,
                                                    'hasSingleUserOrderLimit': 0,
                                                    'hasUnPostAd': 0,
                                                    'isEmail': 0,
                                                    'isKyc': 1,
                                                    'isMobile': 0,
                                                    'nationalLimit': '',
                                                    'orderFinishNumberDay30': 0,
                                                    'registerTimeThreshold': 0,
                                                    'singleUserOrderLimit': 0},
                           'userId': '102420997',
                           'userMaskId': 's32b0539a1ba14f6d90e5c2da0a62e008',
                           'userType': 'PERSONAL',
                           'verificationOrderAmount': '0',
                           'verificationOrderLabels': [],
                           'verificationOrderSwitch': False,
                           'version': 0},
                          {'accountId': '25944052',
                           'authStatus': 1,
                           'authTag': ['VA1', 'BA', 'GA', 'VA', 'VA2'],
                           'ban': False,
                           'baned': False,
                           'blocked': 'N',
                           'createDate': '1741595088000',
                           'currencyId': 'RUB',
                           'executedQuantity': '0.00749876',
                           'fee': '',
                           'finishNum': 192,
                           'frozenQuantity': '0',
                           'id': '1899013551687634944',
                           'isOnline': True,
                           'itemType': 'ORIGIN',
                           'lastLogoutTime': '1755339772',
                           'lastQuantity': '0.04',
                           'makerContact': False,
                           'maxAmount': '391253.05',
                           'minAmount': '20000.00',
                           'nickName': 'TowerOfPower',
                           'orderNum': 193,
                           'paymentPeriod': 15,
                           'payments': ['64', '612', '613', '614'],
                           'premium': '103.98',
                           'price': '9781326.34',
                           'priceType': 1,
                           'quantity': '0.04749876',
                           'recentExecuteRate': 100,
                           'recentOrderNum': 690,
                           'recommend': False,
                           'recommendTag': '',
                           'remark': 'ОТКРЫВАЯ ОРДЕР ВЫ СОГЛАШАЕТЕСЬ С МОИМИ '
                                    'УСЛОВЯМИ\n'
                                    '\n'
                                    'Оплата по СБП\n'
                                    'Оплата принимается только с банков, '
                                    'указанных в сделке\n'
                                    'После оплаты принимаю только чек в формате '
                                    'PDF\n'
                                    'Могу запросить разделение платежа\n'
                                    'Принимаю на карту доверенного лица\n'
                                    'При необходимости могу запросить доп. '
                                    'подтверждения платежа\n'
                                    '\n'
                                    'При переводе не туда - средства не '
                                    'возвращаются\n'
                                    'Третье лицо - фото карты или видео из '
                                    'личного кабинета НА ФОНЕ ордера\n'
                                    'Не принимаю переводы с ИП и пополнения с '
                                    'банкоматов',
                           'side': 1,
                           'status': 10,
                           'symbolInfo': {'buyAd': None,
                                          'buyFeeRate': '',
                                          'currency': {'currencyId': 'RUB',
                                                       'exchangeId': '0',
                                                       'id': '7',
                                                       'orgId': '9001',
                                                       'scale': 2},
                                          'currencyId': 'RUB',
                                          'currencyLowerMaxQuote': '500',
                                          'currencyMaxQuote': '2000000',
                                          'currencyMinQuote': '500',
                                          'exchangeId': '301',
                                          'id': '31',
                                          'itemDownRange': '80',
                                          'itemSideLimit': 3,
                                          'itemUpRange': '120',
                                          'k$1=<SECRET_API_KEY>': '0',
                                          'lowerLimitAlarm': 90,
                                          'orderAutoCancelMinute': 15,
                                          'orderFinishMinute': 10,
                                          'orgId': '9001',
                                          'sellAd': None,
                                          'sellFeeRate': '',
                                          'status': 1,
                                          'token': {'exchangeId': '0',
                                                    'id': '2',
                                                    'orgId': '9001',
                                                    'scale': 8,
                                                    'sequence': 0,
                                                    'tokenId': 'BTC'},
                                          'tokenId': 'BTC',
                                          'tokenMaxQuote': '2',
                                          'tokenMinQuote': '0.00005',
                                          'tradeSide': 9,
                                          'upperLimitAlarm': 110},
                           'tokenId': 'BTC',
                           'tokenName': '',
                           'tradingPreferenceSet': {'completeRateDay30': '0',
                                                    'hasCompleteRateDay30': 0,
                                                    'hasNationalLimit': 0,
                                                    'hasOrderFinishNumberDay30': 0,
                                                    'hasRegisterTime': 1,
                                                    'hasSingleUserOrderLimit': 0,
                                                    'hasUnPostAd': 0,
                                                    'isEmail': 0,
                                                    'isKyc': 1,
                                                    'isMobile': 0,
                                                    'nationalLimit': '',
                                                    'orderFinishNumberDay30': 0,
                                                    'registerTimeThreshold': 30,
                                                    'singleUserOrderLimit': 0},
                           'userId': '25944050',
                           'userMaskId': 's17572d8249664ffbb8f971a9f0be5ac7',
                           'userType': 'PERSONAL',
                           'verificationOrderAmount': '0',
                           'verificationOrderLabels': [],
                           'verificationOrderSwitch': False,
                           'version': 0},
                          {'accountId': '346855517',
                           'authStatus': 2,
                           'authTag': ['GA'],
                           'ban': False,
                           'baned': False,
                           'blocked': 'N',
                           'createDate': '1735376794000',
                           'currencyId': 'RUB',
                           'executedQuantity': '0.00786361',
                           'fee': '',
                           'finishNum': 374,
                           'frozenQuantity': '0',
                           'id': '1872932137490059264',
                           'isOnline': True,
                           'itemType': 'ORIGIN',
                           'lastLogoutTime': '1755334461',
                           'lastQuantity': '0.04',
                           'makerContact': False,
                           'maxAmount': '391328.30',
                           'minAmount': '20000.00',
                           'nickName': 'Bumblebee Coin',
                           'orderNum': 375,
                           'paymentPeriod': 15,
                           'payments': ['64', '581', '613', '614'],
                           'premium': '104',
                           'price': '9783207.73',
                           'priceType': 1,
                           'quantity': '0.04786361',
                           'recentExecuteRate': 100,
                           'recentOrderNum': 606,
                           'recommend': False,
                           'recommendTag': '',
                           'remark': 'Оплата только с банков, указанных в '
                                    'объявлении\n'
                                    'Приму только чек в формате PDF\n'
                                    'Могу запросить дополнительные подтверждения\n'
                                    'Приму третье лицо, условие: фото '
                                    'карты/личного кабинета на фоне сделки\n'
                                    'Принимаю на карту доверенного лица\n'
                                    '\n'
                                    'Не принимаю с Ип, Юр.лиц\n'
                                    'Не принимаю пополнение с банкомата\n'
                                    'Не возвращаю средства при переводе не на '
                                    'тот банк\n'
                                    '\n'
                                    'ПОДСКАЖУ И ПОМОГУ ЕСЛИ, ЧТО-ТО НЕ ПОНЯТНО☑️',
                           'side': 1,
                           'status': 10,
                           'symbolInfo': {'buyAd': None,
                                          'buyFeeRate': '',
                                          'currency': {'currencyId': 'RUB',
                                                       'exchangeId': '0',
                                                       'id': '7',
                                                       'orgId': '9001',
                                                       'scale': 2},
                                          'currencyId': 'RUB',
                                          'currencyLowerMaxQuote': '500',
                                          'currencyMaxQuote': '2000000',
                                          'currencyMinQuote': '500',
                                          'exchangeId': '301',
                                          'id': '31',
                                          'itemDownRange': '80',
                                          'itemSideLimit': 3,
                                          'itemUpRange': '120',
                                          'k$1=<SECRET_API_KEY>': '0',
                                          'lowerLimitAlarm': 90,
                                          'orderAutoCancelMinute': 15,
                                          'orderFinishMinute': 10,
                                          'orgId': '9001',
                                          'sellAd': None,
                                          'sellFeeRate': '',
                                          'status': 1,
                                          'token': {'exchangeId': '0',
                                                    'id': '2',
                                                    'orgId': '9001',
                                                    'scale': 8,
                                                    'sequence': 0,
                                                    'tokenId': 'BTC'},
                                          'tokenId': 'BTC',
                                          'tokenMaxQuote': '2',
                                          'tokenMinQuote': '0.00005',
                                          'tradeSide': 9,
                                          'upperLimitAlarm': 110},
                           'tokenId': 'BTC',
                           'tokenName': '',
                           'tradingPreferenceSet': {'completeRateDay30': '0',
                                                    'hasCompleteRateDay30': 0,
                                                    'hasNationalLimit': 0,
                                                    'hasOrderFinishNumberDay30': 0,
                                                    'hasRegisterTime': 1,
                                                    'hasSingleUserOrderLimit': 0,
                                                    'hasUnPostAd': 0,
                                                    'isEmail': 0,
                                                    'isKyc': 1,
                                                    'isMobile': 0,
                                                    'nationalLimit': '',
                                                    'orderFinishNumberDay30': 0,
                                                    'registerTimeThreshold': 15,
                                                    'singleUserOrderLimit': 0},
                           'userId': '346855512',
                           'userMaskId': 's2963a0dd8d5a4338adecfd867d35da94',
                           'userType': 'PERSONAL',
                           'verificationOrderAmount': '0',
                           'verificationOrderLabels': [],
                           'verificationOrderSwitch': False,
                           'version': 0},
                          {'accountId': '247563211',
                           'authStatus': 1,
                           'authTag': ['VA1', 'BA', 'GA', 'VA', 'VA2'],
                           'ban': False,
                           'baned': False,
                           'blocked': 'N',
                           'createDate': '1734264915000',
                           'currencyId': 'RUB',
                           'executedQuantity': '0',
                           'fee': '',
                           'finishNum': 469,
                           'frozenQuantity': '0',
                           'id': '1868268577701261312',
                           'isOnline': False,
                           'itemType': 'ORIGIN',
                           'lastLogoutTime': '1755341958',
                           'lastQuantity': '0.07000627',
                           'makerContact': True,
                           'maxAmount': '685011.35',
                           'minAmount': '50000.00',
                           'nickName': '🪄KriptoPotter�',
                           'orderNum': 475,
                           'paymentPeriod': 30,
                           'payments': ['581', '382'],
                           'premium': '0',
                           'price': '9785000.00',
                           'priceType': 0,
                           'quantity': '0.07000627',
                           'recentExecuteRate': 98,
                           'recentOrderNum': 423,
                           'recommend': False,
                           'recommendTag': '',
                           'remark': 'Помогу новичкам разобраться.  В приоритете '
                                    'работа с процессингом. Также работаю с 1 и 3 '
                                    'лицами, обменниками, командами.\u2028'
                                    ' Обязательно прошу пруфы по трафику — '
                                    'важно понимать, откуда деньги. Работаю '
                                    'только с чистыми средствами.\u2028'
                                    '\n',
                           'side': 1,
                           'status': 10,
                           'symbolInfo': {'buyAd': None,
                                          'buyFeeRate': '',
                                          'currency': {'currencyId': 'RUB',
                                                       'exchangeId': '0',
                                                       'id': '7',
                                                       'orgId': '9001',
                                                       'scale': 2},
                                          'currencyId': 'RUB',
                                          'currencyLowerMaxQuote': '500',
                                          'currencyMaxQuote': '2000000',
                                          'currencyMinQuote': '500',
                                          'exchangeId': '301',
                                          'id': '31',
                                          'itemDownRange': '80',
                                          'itemSideLimit': 3,
                                          'itemUpRange': '120',
                                          'k$1=<SECRET_API_KEY>': '0',
                                          'lowerLimitAlarm': 90,
                                          'orderAutoCancelMinute': 15,
                                          'orderFinishMinute': 10,
                                          'orgId': '9001',
                                          'sellAd': None,
                                          'sellFeeRate': '',
                                          'status': 1,
                                          'token': {'exchangeId': '0',
                                                    'id': '2',
                                                    'orgId': '9001',
                                                    'scale': 8,
                                                    'sequence': 0,
                                                    'tokenId': 'BTC'},
                                          'tokenId': 'BTC',
                                          'tokenMaxQuote': '2',
                                          'tokenMinQuote': '0.00005',
                                          'tradeSide': 9,
                                          'upperLimitAlarm': 110},
                           'tokenId': 'BTC',
                           'tokenName': '',
                           'tradingPreferenceSet': {'completeRateDay30': '',
                                                    'hasCompleteRateDay30': 0,
                                                    'hasNationalLimit': 0,
                                                    'hasOrderFinishNumberDay30': 0,
                                                    'hasRegisterTime': 0,
                                                    'hasSingleUserOrderLimit': 0,
                                                    'hasUnPostAd': 0,
                                                    'isEmail': 0,
                                                    'isKyc': 1,
                                                    'isMobile': 0,
                                                    'nationalLimit': '',
                                                    'orderFinishNumberDay30': 0,
                                                    'registerTimeThreshold': 0,
                                                    'singleUserOrderLimit': 0},
                           'userId': '247563209',
                           'userMaskId': 's47ed6480a2cc4472b3f9c6968a2c1bf4',
                           'userType': 'PERSONAL',
                           'verificationOrderAmount': '0',
                           'verificationOrderLabels': [],
                           'verificationOrderSwitch': False,
                           'version': 0},
                          {'accountId': '42243042',
                           'authStatus': 1,
                           'authTag': ['VA1', 'GA', 'VA'],
                           'ban': False,
                           'baned': False,
                           'blocked': 'N',
                           'createDate': '1718391766000',
                           'currencyId': 'RUB',
                           'executedQuantity': '0.04446764',
                           'fee': '',
                           'finishNum': 148,
                           'frozenQuantity': '0',
                           'id': '1801691767332270080',
                           'isOnline': False,
                           'itemType': 'ORIGIN',
                           'lastLogoutTime': '1755342093',
                           'lastQuantity': '0.01692052',
                           'makerContact': True,
                           'maxAmount': '165696.13',
                           'minAmount': '25000.00',
                           'nickName': 'CriptoChanger',
                           'orderNum': 148,
                           'paymentPeriod': 15,
                           'payments': ['64', '613', '382'],
                           'premium': '104.1',
                           'price': '9792614.66',
                           'priceType': 1,
                           'quantity': '0.06138816',
                           'recentExecuteRate': 100,
                           'recentOrderNum': 77,
                           'recommend': False,
                           'recommendTag': '',
                           'remark': 'Всем привет\n'
                                    '\n'
                                    'Быстрые ответы, онлайн поддержка!\n'
                                    '\n'
                                    'Чек  об оплате присылайте в чат сделки , '
                                    'комментарии к платежу не нужны!\n'
                                    '\n'
                                    'Мои реквизиты ОТ ПЕРВОГО ЛИЦА - 100 % '
                                    'гарантия надёжности и доверительность '
                                    'проведения банковских операций!\n'
                                    '\n'
                                    'СБП или внутрибанковский перевод - '
                                    '(телефон и какой банк подскажу в чате в '
                                    'зависимости от загрузки).\n'
                                    '\n'
                                    ' ОПЛАТА ОТ ПЕРВЫХ ЛИЦ, Ф.И.О на бирже '
                                    'должно соответствовать Ф.И.О отправителя '
                                    'денежных средств в банке!\n'
                                    '\n'
                                    ' Благодарю за прочтение информации и '
                                    'соблюдение условий, с наилучшими '
                                    'пожеланиями, CryptoChanger!\n'
                                    '\n'
                                    ' P.S.: Если оставляете отзыв, пишите об '
                                    'этом в чате, отвечу взаимностью!',
                           'side': 1,
                           'status': 10,
                           'symbolInfo': {'buyAd': None,
                                          'buyFeeRate': '',
                                          'currency': {'currencyId': 'RUB',
                                                       'exchangeId': '0',
                                                       'id': '7',
                                                       'orgId': '9001',
                                                       'scale': 2},
                                          'currencyId': 'RUB',
                                          'currencyLowerMaxQuote': '500',
                                          'currencyMaxQuote': '2000000',
                                          'currencyMinQuote': '500',
                                          'exchangeId': '301',
                                          'id': '31',
                                          'itemDownRange': '80',
                                          'itemSideLimit': 3,
                                          'itemUpRange': '120',
                                          'k$1=<SECRET_API_KEY>': '0',
                                          'lowerLimitAlarm': 90,
                                          'orderAutoCancelMinute': 15,
                                          'orderFinishMinute': 10,
                                          'orgId': '9001',
                                          'sellAd': None,
                                          'sellFeeRate': '',
                                          'status': 1,
                                          'token': {'exchangeId': '0',
                                                    'id': '2',
                                                    'orgId': '9001',
                                                    'scale': 8,
                                                    'sequence': 0,
                                                    'tokenId': 'BTC'},
                                          'tokenId': 'BTC',
                                          'tokenMaxQuote': '2',
                                          'tokenMinQuote': '0.00005',
                                          'tradeSide': 9,
                                          'upperLimitAlarm': 110},
                           'tokenId': 'BTC',
                           'tokenName': '',
                           'tradingPreferenceSet': {'completeRateDay30': '0',
                                                    'hasCompleteRateDay30': 0,
                                                    'hasNationalLimit': 1,
                                                    'hasOrderFinishNumberDay30': 0,
                                                    'hasRegisterTime': 1,
                                                    'hasSingleUserOrderLimit': 0,
                                                    'hasUnPostAd': 0,
                                                    'isEmail': 0,
                                                    'isKyc': 1,
                                                    'isMobile': 0,
                                                    'nationalLimit': 'RUS',
                                                    'orderFinishNumberDay30': 0,
                                                    'registerTimeThreshold': 15,
                                                    'singleUserOrderLimit': 0},
                           'userId': '42243041',
                           'userMaskId': 'scf8df548dede4f66a9c582df197fa936',
                           'userType': 'PERSONAL',
                           'verificationOrderAmount': '0',
                           'verificationOrderLabels': [],
                           'verificationOrderSwitch': False,
                           'version': 0},
                          {'accountId': '103702372',
                           'authStatus': 1,
                           'authTag': ['VA1', 'BA', 'GA', 'VA', 'VA2'],
                           'ban': False,
                           'baned': False,
                           'blocked': 'N',
                           'createDate': '1700432788000',
                           'currencyId': 'RUB',
                           'executedQuantity': '0.00904095',
                           'fee': '',
                           'finishNum': 1916,
                           'frozenQuantity': '0',
                           'id': '1726366353289940992',
                           'isOnline': True,
                           'itemType': 'ORIGIN',
                           'lastLogoutTime': '1755339196',
                           'lastQuantity': '0.10711624',
                           'makerContact': True,
                           'maxAmount': '1050661.04',
                           'minAmount': '50000.00',
                           'nickName': 'CityExchange',
                           'orderNum': 1931,
                           'paymentPeriod': 30,
                           'payments': ['64', '382'],
                           'premium': '104.27',
                           'price': '9808606.44',
                           'priceType': 1,
                           'quantity': '0.11615719',
                           'recentExecuteRate': 100,
                           'recentOrderNum': 362,
                           'recommend': False,
                           'recommendTag': '',
                           'remark': 'Принимаем оплату от первых лиц \n'
                                    'Принимаем оплату от третьих лиц -  для '
                                    'этого нужно сделать фото пластиковой карты '
                                    'отправителя на фоне сделки и отправить в '
                                    'чат\n'
                                    'Принимаем по СБП(По телефону) , просим не '
                                    'заходить в сделку если не готовы оплатить на '
                                    'другой банк \n'
                                    ' Круглосуточный обмен криптовалюты, топовая '
                                    'связь 24/7\n'
                                    ' Принимаем на карту доверенного лица\n'
                                    '\n'
                                    ' ВНИМАНИЕ ВСЕ МОШЕННИКИ/ХУДОЖНИКИ МИМО, '
                                    'ВСЕ ПОСТУПЛЕНИЯ ПРОВЕРЯЮ В ПРИЛОЖЕНИИ БАНКА, '
                                    'ЛИЧНЫЙ КАБИНЕТ НА РУКАХ! ЕСЛИ УВИЖУ '
                                    'ОТРИСОВАННЫЙ ЧЕК В ЧАТЕ СДЕЛКИ БЕЗ '
                                    'ПОСТУПЛЕНИЯ В ПРИЛОЖЕНИИ БАНКА -  ЖАЛОБА В '
                                    'ВИП ПОДДЕРЖКУ БАЙБИТ И АПЕЛЛЯЦИЯ '
                                    'ПРИОРИТЕТНАЯ СРАЗУ ЖЕ БЕЗ КАКИХ ЛИБО '
                                    'СОЖАЛЕНИЙ  МГНОВЕННЫЙ БЛОК БУДЕТ ОБЕСПЕЧЕН '
                                    '',
                           'side': 1,
                           'status': 10,
                           'symbolInfo': {'buyAd': None,
                                          'buyFeeRate': '',
                                          'currency': {'currencyId': 'RUB',
                                                       'exchangeId': '0',
                                                       'id': '7',
                                                       'orgId': '9001',
                                                       'scale': 2},
                                          'currencyId': 'RUB',
                                          'currencyLowerMaxQuote': '500',
                                          'currencyMaxQuote': '2000000',
                                          'currencyMinQuote': '500',
                                          'exchangeId': '301',
                                          'id': '31',
                                          'itemDownRange': '80',
                                          'itemSideLimit': 3,
                                          'itemUpRange': '120',
                                          'k$1=<SECRET_API_KEY>': '0',
                                          'lowerLimitAlarm': 90,
                                          'orderAutoCancelMinute': 15,
                                          'orderFinishMinute': 10,
                                          'orgId': '9001',
                                          'sellAd': None,
                                          'sellFeeRate': '',
                                          'status': 1,
                                          'token': {'exchangeId': '0',
                                                    'id': '2',
                                                    'orgId': '9001',
                                                    'scale': 8,
                                                    'sequence': 0,
                                                    'tokenId': 'BTC'},
                                          'tokenId': 'BTC',
                                          'tokenMaxQuote': '2',
                                          'tokenMinQuote': '0.00005',
                                          'tradeSide': 9,
                                          'upperLimitAlarm': 110},
                           'tokenId': 'BTC',
                           'tokenName': '',
                           'tradingPreferenceSet': None,
                           'userId': '103702371',
                           'userMaskId': 's98d3361dcb014ae89baf55f90f80df69',
                           'userType': 'PERSONAL',
                           'verificationOrderAmount': '0',
                           'verificationOrderLabels': [],
                           'verificationOrderSwitch': False,
                           'version': 0}]},
    'ret_code': 0,
    'ret_msg': 'SUCCESS',
    'time_now': '1755342250.367191'
}