# utils/eth_response.py
ETH_RESPONSE = {
    'ext_code': '',
    'ext_info': {},
    'result': {'count': 22,
               'items': [{'accountId': '132936878',
                          'authStatus': 1,
                          'authTag': ['VA1', 'GA', 'VA'],
                          'ban': False,
                          'baned': False,
                          'blocked': 'N',
                          'createDate': '1753445913000',
                          'currencyId': 'RUB',
                          'executedQuantity': '0',
                          'fee': '',
                          'finishNum': 65,
                          'frozenQuantity': '0',
                          'id': '1948719513582186496',
                          'isOnline': True,
                          'itemType': 'ORIGIN',
                          'lastLogoutTime': '1756043850',
                          'lastQuantity': '0.38339341',
                          'makerContact': True,
                          'maxAmount': '150000.00',
                          'minAmount': '20000.00',
                          'nickName': 'Wiza61',
                          'orderNum': 65,
                          'paymentPeriod': 30,
                          'payments': ['64', '382'],
                          'premium': '104.9',
                          'price': '395971.70',
                          'priceType': 1,
                          'quantity': '0.38339341',
                          'recentExecuteRate': 96,
                          'recentOrderNum': 793,
                          'recommend': False,
                          'recommendTag': '',
                          'remark': 'Со всех банков по СБП (НОМЕР ТЕЛ)\n'
                                 '                                                                                                                             '
                                 'Принимаю  c ЛИЧНЫХ КАРТ, и карт '
                                 'родственников (однофамильцев) \n'
                                 '\n'
                                 'Работаю быстро\n'
                                 '(ЕСЛИ от 3 то фото ЛК на фоне сделки)\n'
                                 'Новым пользователям помогу разобраться \n'
                                 '\n'
                                 'Если 3 лица:требуется минимальное '
                                 'подтверждение трафика!Обменники, товарки, - '
                                 'ЗАХОДИТЕ',
                          'side': 1,
                          'status': 10,
                          'symbolInfo': {'buyAd': None,
                                         'buyFeeRate': '',
                                         'currency': {'currencyId': 'RUB',
                                                      'exchangeId': '0',
                                                      'id': '7',
                                                      'orgId': '9001',
                                                      'scale': 2},
                                         'currencyId': 'RUB',
                                         'currencyLowerMaxQuote': '500',
                                         'currencyMaxQuote': '3500000',
                                         'currencyMinQuote': '500',
                                         'exchangeId': '301',
                                         'id': '36',
                                         'itemDownRange': '80',
                                         'itemSideLimit': 3,
                                         'itemUpRange': '120',
                                         'k$1=<SECRET_API_KEY>': '0',
                                         'lowerLimitAlarm': 90,
                                         'orderAutoCancelMinute': 15,
                                         'orderFinishMinute': 10,
                                         'orgId': '9001',
                                         'sellAd': None,
                                         'sellFeeRate': '',
                                         'status': 1,
                                         'token': {'exchangeId': '0',
                                                   'id': '3',
                                                   'orgId': '9001',
                                                   'scale': 8,
                                                   'sequence': 0,
                                                   'tokenId': 'ETH'},
                                         'tokenId': 'ETH',
                                         'tokenMaxQuote': '30',
                                         'tokenMinQuote': '0.001',
                                         'tradeSide': 9,
                                         'upperLimitAlarm': 110},
                          'tokenId': 'ETH',
                          'tokenName': '',
                          'tradingPreferenceSet': {'completeRateDay30': '',
                                                   'hasCompleteRateDay30': 0,
                                                   'hasNationalLimit': 0,
                                                   'hasOrderFinishNumberDay30': 0,
                                                   'hasRegisterTime': 0,
                                                   'hasSingleUserOrderLimit': 0,
                                                   'hasUnPostAd': 0,
                                                   'isEmail': 0,
                                                   'isKyc': 1,
                                                   'isMobile': 0,
                                                   'nationalLimit': '',
                                                   'orderFinishNumberDay30': 0,
                                                   'registerTimeThreshold': 0,
                                                   'singleUserOrderLimit': 0},
                          'userId': '132936876',
                          'userMaskId': 'se713438553884d74b0e6a5ae735fab2d',
                          'userType': 'PERSONAL',
                          'verificationOrderAmount': '0',
                          'verificationOrderLabels': [],
                          'verificationOrderSwitch': False,
                          'version': 0},
                         {'accountId': '247563211',
                          'authStatus': 1,
                          'authTag': ['VA1', 'BA', 'GA', 'VA', 'VA2'],
                          'ban': False,
                          'baned': False,
                          'blocked': 'N',
                          'createDate': '1737103072000',
                          'currencyId': 'RUB',
                          'executedQuantity': '0',
                          'fee': '',
                          'finishNum': 125,
                          'frozenQuantity': '0',
                          'id': '1880172671154266112',
                          'isOnline': False,
                          'itemType': 'ORIGIN',
                          'lastLogoutTime': '1756102116',
                          'lastQuantity': '1.00099497',
                          'makerContact': True,
                          'maxAmount': '396394.00',
                          'minAmount': '50000.00',
                          'nickName': '🪄KriptoPotter�',
                          'orderNum': 126,
                          'paymentPeriod': 30,
                          'payments': ['581', '382'],
                          'premium': '0',
                          'price': '396000.00',
                          'priceType': 0,
                          'quantity': '1.00099497',
                          'recentExecuteRate': 98,
                          'recentOrderNum': 253,
                          'recommend': False,
                          'recommendTag': '',
                          'remark': ' В приоритете работа с процессингом. Также '
                                 'работаю с 1 и 3 лицами, обменниками, '
                                 'командами.\u2028'
                                 ' Обязательно прошу пруфы по трафику — '
                                 'важно понимать, откуда деньги. Работаю '
                                 'только с чистыми средствами. Принимаю на '
                                 'карту доверенных лиц.',
                          'side': 1,
                          'status': 10,
                          'symbolInfo': {'buyAd': None,
                                         'buyFeeRate': '',
                                         'currency': {'currencyId': 'RUB',
                                                      'exchangeId': '0',
                                                      'id': '7',
                                                      'orgId': '9001',
                                                      'scale': 2},
                                         'currencyId': 'RUB',
                                         'currencyLowerMaxQuote': '500',
                                         'currencyMaxQuote': '3500000',
                                         'currencyMinQuote': '500',
                                         'exchangeId': '301',
                                         'id': '36',
                                         'itemDownRange': '80',
                                         'itemSideLimit': 3,
                                         'itemUpRange': '120',
                                         'k$1=<SECRET_API_KEY>': '0',
                                         'lowerLimitAlarm': 90,
                                         'orderAutoCancelMinute': 15,
                                         'orderFinishMinute': 10,
                                         'orgId': '9001',
                                         'sellAd': None,
                                         'sellFeeRate': '',
                                         'status': 1,
                                         'token': {'exchangeId': '0',
                                                   'id': '3',
                                                   'orgId': '9001',
                                                   'scale': 8,
                                                   'sequence': 0,
                                                   'tokenId': 'ETH'},
                                         'tokenId': 'ETH',
                                         'tokenMaxQuote': '30',
                                         'tokenMinQuote': '0.001',
                                         'tradeSide': 9,
                                         'upperLimitAlarm': 110},
                          'tokenId': 'ETH',
                          'tokenName': '',
                          'tradingPreferenceSet': {'completeRateDay30': '',
                                                   'hasCompleteRateDay30': 0,
                                                   'hasNationalLimit': 0,
                                                   'hasOrderFinishNumberDay30': 0,
                                                   'hasRegisterTime': 0,
                                                   'hasSingleUserOrderLimit': 0,
                                                   'hasUnPostAd': 0,
                                                   'isEmail': 0,
                                                   'isKyc': 1,
                                                   'isMobile': 0,
                                                   'nationalLimit': '',
                                                   'orderFinishNumberDay30': 0,
                                                   'registerTimeThreshold': 0,
                                                   'singleUserOrderLimit': 0},
                          'userId': '247563209',
                          'userMaskId': 's47ed6480a2cc4472b3f9c6968a2c1bf4',
                          'userType': 'PERSONAL',
                          'verificationOrderAmount': '0',
                          'verificationOrderLabels': [],
                          'verificationOrderSwitch': False,
                          'version': 0},
                         {'accountId': '134013463',
                          'authStatus': 1,
                          'authTag': ['VA1', 'GA', 'VA', 'VA2'],
                          'ban': False,
                          'baned': False,
                          'blocked': 'N',
                          'createDate': '1738142554000',
                          'currencyId': 'RUB',
                          'executedQuantity': '0',
                          'fee': '',
                          'finishNum': 81,
                          'frozenQuantity': '0',
                          'id': '1884532574960922624',
                          'isOnline': True,
                          'itemType': 'ORIGIN',
                          'lastLogoutTime': '1756102414',
                          'lastQuantity': '1',
                          'makerContact': False,
                          'maxAmount': '396349.18',
                          'minAmount': '20000.00',
                          'nickName': 'XO Delta',
                          'orderNum': 82,
                          'paymentPeriod': 15,
                          'payments': ['64', '49', '612', '613', '614'],
                          'premium': '105',
                          'price': '396349.18',
                          'priceType': 1,
                          'quantity': '1',
                          'recentExecuteRate': 99,
                          'recentOrderNum': 588,
                          'recommend': False,
                          'recommendTag': '',
                          'remark': '-Приму чек только в ПДФ формате на почту\n'
                                 '-Могу попросить разделить платеж\n'
                                 '-Могу запросить доказательства платежа\n'
                                 '-Третье лицо только с фото карты на фоне '
                                 'сделки\n'
                                 '-Оплата на карту доверенного лица\n'
                                 '-Если вы перевели в другой банк, возврата '
                                 'нет\n'
                                 '\n'
                                 'НЕ ПРИНИМАЮ ПОПОЛНЕНИЕ ЧЕРЕЗ БАНКОМАТ \n'
                                 'НЕ ПРИНИМАЮ С ЮР. ЛИЦ\n'
                                 '-Приму чек только в ПДФ формате на почту\n'
                                 '-Могу попросить разделить платеж\n'
                                 '-Могу запросить доказательства платежа\n'
                                 '-Третье лицо только с фото карты на фоне '
                                 'сделки\n'
                                 '-Оплата на карту доверенного лица\n'
                                 '-Если вы перевели в другой банк, возврата '
                                 'нет\n'
                                 '\n'
                                 'НЕ ПРИНИМАЮ ПОПОЛНЕНИЕ ЧЕРЕЗ БАНКОМАТ \n'
                                 'НЕ ПРИНИМАЮ С ЮР. ЛИЦ',
                          'side': 1,
                          'status': 10,
                          'symbolInfo': {'buyAd': None,
                                         'buyFeeRate': '',
                                         'currency': {'currencyId': 'RUB',
                                                      'exchangeId': '0',
                                                      'id': '7',
                                                      'orgId': '9001',
                                                      'scale': 2},
                                         'currencyId': 'RUB',
                                         'currencyLowerMaxQuote': '500',
                                         'currencyMaxQuote': '3500000',
                                         'currencyMinQuote': '500',
                                         'exchangeId': '301',
                                         'id': '36',
                                         'itemDownRange': '80',
                                         'itemSideLimit': 3,
                                         'itemUpRange': '120',
                                         'k$1=<SECRET_API_KEY>': '0',
                                         'lowerLimitAlarm': 90,
                                         'orderAutoCancelMinute': 15,
                                         'orderFinishMinute': 10,
                                         'orgId': '9001',
                                         'sellAd': None,
                                         'sellFeeRate': '',
                                         'status': 1,
                                         'token': {'exchangeId': '0',
                                                   'id': '3',
                                                   'orgId': '9001',
                                                   'scale': 8,
                                                   'sequence': 0,
                                                   'tokenId': 'ETH'},
                                         'tokenId': 'ETH',
                                         'tokenMaxQuote': '30',
                                         'tokenMinQuote': '0.001',
                                         'tradeSide': 9,
                                         'upperLimitAlarm': 110},
                          'tokenId': 'ETH',
                          'tokenName': '',
                          'tradingPreferenceSet': {'completeRateDay30': '0',
                                                   'hasCompleteRateDay30': 0,
                                                   'hasNationalLimit': 0,
                                                   'hasOrderFinishNumberDay30': 0,
                                                   'hasRegisterTime': 1,
                                                   'hasSingleUserOrderLimit': 0,
                                                   'hasUnPostAd': 0,
                                                   'isEmail': 0,
                                                   'isKyc': 1,
                                                   'isMobile': 0,
                                                   'nationalLimit': '',
                                                   'orderFinishNumberDay30': 0,
                                                   'registerTimeThreshold': 30,
                                                   'singleUserOrderLimit': 0},
                          'userId': '134013462',
                          'userMaskId': 'se8cd64b63154498c9916bb349ddfc9dc',
                          'userType': 'PERSONAL',
                          'verificationOrderAmount': '0',
                          'verificationOrderLabels': [],
                          'verificationOrderSwitch': False,
                          'version': 0},
                         {'accountId': '346855517',
                          'authStatus': 2,
                          'authTag': ['GA'],
                          'ban': False,
                          'baned': False,
                          'blocked': 'N',
                          'createDate': '1753780347000',
                          'currencyId': 'RUB',
                          'executedQuantity': '0',
                          'fee': '',
                          'finishNum': 32,
                          'frozenQuantity': '0',
                          'id': '1950122234884481024',
                          'isOnline': True,
                          'itemType': 'ORIGIN',
                          'lastLogoutTime': '1756102671',
                          'lastQuantity': '1',
                          'makerContact': False,
                          'maxAmount': '401633.83',
                          'minAmount': '20000.00',
                          'nickName': 'Bumblebee Coin',
                          'orderNum': 32,
                          'paymentPeriod': 15,
                          'payments': ['64', '581', '613', '614'],
                          'premium': '106.4',
                          'price': '401633.83',
                          'priceType': 1,
                          'quantity': '1',
                          'recentExecuteRate': 100,
                          'recentOrderNum': 650,
                          'recommend': False,
                          'recommendTag': '',
                          'remark': 'Оплата только с банков, указанных в '
                                 'объявлении\n'
                                 'Приму только чек в формате PDF\n'
                                 'Могу запросить дополнительные подтверждения\n'
                                 'Приму третье лицо, условие: фото '
                                 'карты/личного кабинета на фоне сделки\n'
                                 'Принимаю на карту доверенного лица\n'
                                 '\n'
                                 'Не принимаю с Ип, Юр.лиц\n'
                                 'Не принимаю пополнение с банкомата\n'
                                 'Не возвращаю средства при переводе не на '
                                 'тот банк\n'
                                 '\n'
                                 'ПОДСКАЖУ И ПОМОГУ ЕСЛИ, ЧТО-ТО НЕ ПОНЯТНО',
                          'side': 1,
                          'status': 10,
                          'symbolInfo': {'buyAd': None,
                                         'buyFeeRate': '',
                                         'currency': {'currencyId': 'RUB',
                                                      'exchangeId': '0',
                                                      'id': '7',
                                                      'orgId': '9001',
                                                      'scale': 2},
                                         'currencyId': 'RUB',
                                         'currencyLowerMaxQuote': '500',
                                         'currencyMaxQuote': '3500000',
                                         'currencyMinQuote': '500',
                                         'exchangeId': '301',
                                         'id': '36',
                                         'itemDownRange': '80',
                                         'itemSideLimit': 3,
                                         'itemUpRange': '120',
                                         'k$1=<SECRET_API_KEY>': '0',
                                         'lowerLimitAlarm': 90,
                                         'orderAutoCancelMinute': 15,
                                         'orderFinishMinute': 10,
                                         'orgId': '9001',
                                         'sellAd': None,
                                         'sellFeeRate': '',
                                         'status': 1,
                                         'token': {'exchangeId': '0',
                                                   'id': '3',
                                                   'orgId': '9001',
                                                   'scale': 8,
                                                   'sequence': 0,
                                                   'tokenId': 'ETH'},
                                         'tokenId': 'ETH',
                                         'tokenMaxQuote': '30',
                                         'tokenMinQuote': '0.001',
                                         'tradeSide': 9,
                                         'upperLimitAlarm': 110},
                          'tokenId': 'ETH',
                          'tokenName': '',
                          'tradingPreferenceSet': {'completeRateDay30': '0',
                                                   'hasCompleteRateDay30': 0,
                                                   'hasNationalLimit': 0,
                                                   'hasOrderFinishNumberDay30': 0,
                                                   'hasRegisterTime': 1,
                                                   'hasSingleUserOrderLimit': 0,
                                                   'hasUnPostAd': 0,
                                                   'isEmail': 0,
                                                   'isKyc': 1,
                                                   'isMobile': 0,
                                                   'nationalLimit': '',
                                                   'orderFinishNumberDay30': 0,
                                                   'registerTimeThreshold': 30,
                                                   'singleUserOrderLimit': 0},
                          'userId': '346855512',
                          'userMaskId': 's2963a0dd8d5a4338adecfd867d35da94',
                          'userType': 'PERSONAL',
                          'verificationOrderAmount': '0',
                          'verificationOrderLabels': [],
                          'verificationOrderSwitch': False,
                          'version': 0},
                         {'accountId': '34165697',
                          'authStatus': 2,
                          'authTag': ['GA'],
                          'ban': False,
                          'baned': False,
                          'blocked': 'N',
                          'createDate': '1755853085000',
                          'currencyId': 'RUB',
                          'executedQuantity': '0.05040417',
                          'fee': '',
                          'finishNum': 4,
                          'frozenQuantity': '0',
                          'id': '1958815926561456128',
                          'isOnline': True,
                          'itemType': 'ORIGIN',
                          'lastLogoutTime': '1756089217',
                          'lastQuantity': '0.21559583',
                          'makerContact': False,
                          'maxAmount': '86590.57',
                          'minAmount': '20000.00',
                          'nickName': 'byasha_88',
                          'orderNum': 4,
                          'paymentPeriod': 30,
                          'payments': ['64', '382'],
                          'premium': '106.4',
                          'price': '401633.83',
                          'priceType': 1,
                          'quantity': '0.266',
                          'recentExecuteRate': 98,
                          'recentOrderNum': 246,
                          'recommend': False,
                          'recommendTag': '',
                          'remark': 'Принимаю как 1 так и 3 лица. Строго 1 '
                                 'платежом. Чек обязательно. По сбп с любого '
                                 'банка. При подозрении в мошенничестве могу '
                                 'запросить скрин с истории банка/выписку по '
                                 'счету/карту на фоне сделки. Лк на руках '
                                 'обязательно',
                          'side': 1,
                          'status': 10,
                          'symbolInfo': {'buyAd': None,
                                         'buyFeeRate': '',
                                         'currency': {'currencyId': 'RUB',
                                                      'exchangeId': '0',
                                                      'id': '7',
                                                      'orgId': '9001',
                                                      'scale': 2},
                                         'currencyId': 'RUB',
                                         'currencyLowerMaxQuote': '500',
                                         'currencyMaxQuote': '3500000',
                                         'currencyMinQuote': '500',
                                         'exchangeId': '301',
                                         'id': '36',
                                         'itemDownRange': '80',
                                         'itemSideLimit': 3,
                                         'itemUpRange': '120',
                                         'k$1=<SECRET_API_KEY>': '0',
                                         'lowerLimitAlarm': 90,
                                         'orderAutoCancelMinute': 15,
                                         'orderFinishMinute': 10,
                                         'orgId': '9001',
                                         'sellAd': None,
                                         'sellFeeRate': '',
                                         'status': 1,
                                         'token': {'exchangeId': '0',
                                                   'id': '3',
                                                   'orgId': '9001',
                                                   'scale': 8,
                                                   'sequence': 0,
                                                   'tokenId': 'ETH'},
                                         'tokenId': 'ETH',
                                         'tokenMaxQuote': '30',
                                         'tokenMinQuote': '0.001',
                                         'tradeSide': 9,
                                         'upperLimitAlarm': 110},
                          'tokenId': 'ETH',
                          'tokenName': '',
                          'tradingPreferenceSet': {'completeRateDay30': '',
                                                   'hasCompleteRateDay30': 0,
                                                   'hasNationalLimit': 0,
                                                   'hasOrderFinishNumberDay30': 0,
                                                   'hasRegisterTime': 0,
                                                   'hasSingleUserOrderLimit': 0,
                                                   'hasUnPostAd': 0,
                                                   'isEmail': 0,
                                                   'isKyc': 1,
                                                   'isMobile': 0,
                                                   'nationalLimit': '',
                                                   'orderFinishNumberDay30': 0,
                                                   'registerTimeThreshold': 0,
                                                   'singleUserOrderLimit': 0},
                          'userId': '34165695',
                          'userMaskId': 'sedbdf6d47c254befa63a578d5c5d651c',
                          'userType': 'PERSONAL',
                          'verificationOrderAmount': '0',
                          'verificationOrderLabels': [],
                          'verificationOrderSwitch': False,
                          'version': 0},
                         {'accountId': '125993949',
                          'authStatus': 1,
                          'authTag': ['VA1', 'GA', 'VA', 'VA2'],
                          'ban': False,
                          'baned': False,
                          'blocked': 'N',
                          'createDate': '1741784974000',
                          'currencyId': 'RUB',
                          'executedQuantity': '2.96195861',
                          'fee': '',
                          'finishNum': 116,
                          'frozenQuantity': '0',
                          'id': '1899809993422655488',
                          'isOnline': True,
                          'itemType': 'ORIGIN',
                          'lastLogoutTime': '1756102912',
                          'lastQuantity': '2.13012126',
                          'makerContact': True,
                          'maxAmount': '500000.00',
                          'minAmount': '20000.00',
                          'nickName': 'jestergg',
                          'orderNum': 116,
                          'paymentPeriod': 15,
                          'payments': ['64', '382'],
                          'premium': '110',
                          'price': '415222.95',
                          'priceType': 1,
                          'quantity': '5.09207987',
                          'recentExecuteRate': 99,
                          'recentOrderNum': 1466,
                          'recommend': False,
                          'recommendTag': '',
                          'remark': 'по сбп / спасибо за сделку ',
                          'side': 1,
                          'status': 10,
                          'symbolInfo': {'buyAd': None,
                                         'buyFeeRate': '',
                                         'currency': {'currencyId': 'RUB',
                                                      'exchangeId': '0',
                                                      'id': '7',
                                                      'orgId': '9001',
                                                      'scale': 2},
                                         'currencyId': 'RUB',
                                         'currencyLowerMaxQuote': '500',
                                         'currencyMaxQuote': '3500000',
                                         'currencyMinQuote': '500',
                                         'exchangeId': '301',
                                         'id': '36',
                                         'itemDownRange': '80',
                                         'itemSideLimit': 3,
                                         'itemUpRange': '120',
                                         'k$1=<SECRET_API_KEY>': '0',
                                         'lowerLimitAlarm': 90,
                                         'orderAutoCancelMinute': 15,
                                         'orderFinishMinute': 10,
                                         'orgId': '9001',
                                         'sellAd': None,
                                         'sellFeeRate': '',
                                         'status': 1,
                                         'token': {'exchangeId': '0',
                                                   'id': '3',
                                                   'orgId': '9001',
                                                   'scale': 8,
                                                   'sequence': 0,
                                                   'tokenId': 'ETH'},
                                         'tokenId': 'ETH',
                                         'tokenMaxQuote': '30',
                                         'tokenMinQuote': '0.001',
                                         'tradeSide': 9,
                                         'upperLimitAlarm': 110},
                          'tokenId': 'ETH',
                          'tokenName': '',
                          'tradingPreferenceSet': {'completeRateDay30': '0',
                                                   'hasCompleteRateDay30': 0,
                                                   'hasNationalLimit': 1,
                                                   'hasOrderFinishNumberDay30': 0,
                                                   'hasRegisterTime': 0,
                                                   'hasSingleUserOrderLimit': 0,
                                                   'hasUnPostAd': 0,
                                                   'isEmail': 0,
                                                   'isKyc': 1,
                                                   'isMobile': 0,
                                                   'nationalLimit': 'RUS',
                                                   'orderFinishNumberDay30': 0,
                                                   'registerTimeThreshold': 0,
                                                   'singleUserOrderLimit': 0},
                          'userId': '125993947',
                          'userMaskId': 's0e88ff212065460f84323f669180bc56',
                          'userType': 'PERSONAL',
                          'verificationOrderAmount': '0',
                          'verificationOrderLabels': [],
                          'verificationOrderSwitch': False,
                          'version': 0},
                         {'accountId': '31010708',
                          'authStatus': 1,
                          'authTag': ['VA1', 'BA', 'GA', 'VA', 'VA2', 'VA3'],
                          'ban': False,
                          'baned': False,
                          'blocked': 'N',
                          'createDate': '1681924366000',
                          'currencyId': 'RUB',
                          'executedQuantity': '4.09990333',
                          'fee': '',
                          'finishNum': 1206,
                          'frozenQuantity': '0',
                          'id': '1648736405443457024',
                          'isOnline': True,
                          'itemType': 'ORIGIN',
                          'lastLogoutTime': '1755977099',
                          'lastQuantity': '0.32102943',
                          'makerContact': True,
                          'maxAmount': '135470.98',
                          'minAmount': '20000.00',
                          'nickName': 'Wins!',
                          'orderNum': 1207,
                          'paymentPeriod': 15,
                          'payments': ['64', '1', '382'],
                          'premium': '0',
                          'price': '421989.30',
                          'priceType': 0,
                          'quantity': '4.42093276',
                          'recentExecuteRate': 99,
                          'recentOrderNum': 1556,
                          'recommend': False,
                          'recommendTag': '',
                          'remark': 'Доброго времени суток,\n'
                                 'Принимаю со всех банков РФ работаю по Сбп\n'
                                 'НЕ БЕЛЫЙ ТРЕУГОЛ, реквизиты выдаю  '
                                 'мгновенно, отпускаю монеты сразу после '
                                 'оплаты\n'
                                 'не принимаю от 3 лиц\n'
                                 'Принимаю на карту доверенного лица\n'
                                 'При долгой транзакции или при подозрении '
                                 'на мошенничество могу запросить фото карты '
                                 'на фоне сделки или верну перевод обратно '
                                 'отправителю',
                          'side': 1,
                          'status': 10,
                          'symbolInfo': {'buyAd': None,
                                         'buyFeeRate': '',
                                         'currency': {'currencyId': 'RUB',
                                                      'exchangeId': '0',
                                                      'id': '7',
                                                      'orgId': '9001',
                                                      'scale': 2},
                                         'currencyId': 'RUB',
                                         'currencyLowerMaxQuote': '500',
                                         'currencyMaxQuote': '3500000',
                                         'currencyMinQuote': '500',
                                         'exchangeId': '301',
                                         'id': '36',
                                         'itemDownRange': '80',
                                         'itemSideLimit': 3,
                                         'itemUpRange': '120',
                                         'k$1=<SECRET_API_KEY>': '0',
                                         'lowerLimitAlarm': 90,
                                         'orderAutoCancelMinute': 15,
                                         'orderFinishMinute': 10,
                                         'orgId': '9001',
                                         'sellAd': None,
                                         'sellFeeRate': '',
                                         'status': 1,
                                         'token': {'exchangeId': '0',
                                                   'id': '3',
                                                   'orgId': '9001',
                                                   'scale': 8,
                                                   'sequence': 0,
                                                   'tokenId': 'ETH'},
                                         'tokenId': 'ETH',
                                         'tokenMaxQuote': '30',
                                         'tokenMinQuote': '0.001',
                                         'tradeSide': 9,
                                         'upperLimitAlarm': 110},
                          'tokenId': 'ETH',
                          'tokenName': '',
                          'tradingPreferenceSet': {'completeRateDay30': '85',
                                                   'hasCompleteRateDay30': 0,
                                                   'hasNationalLimit': 0,
                                                   'hasOrderFinishNumberDay30': 0,
                                                   'hasRegisterTime': 1,
                                                   'hasSingleUserOrderLimit': 0,
                                                   'hasUnPostAd': 0,
                                                   'isEmail': 0,
                                                   'isKyc': 1,
                                                   'isMobile': 0,
                                                   'nationalLimit': '',
                                                   'orderFinishNumberDay30': 0,
                                                   'registerTimeThreshold': 30,
                                                   'singleUserOrderLimit': 0},
                          'userId': '31010707',
                          'userMaskId': 's3577fdaee2c04706a9308ccfc0558c53',
                          'userType': 'PERSONAL',
                          'verificationOrderAmount': '0',
                          'verificationOrderLabels': [],
                          'verificationOrderSwitch': False,
                          'version': 0},
                         {'accountId': '25944052',
                          'authStatus': 1,
                          'authTag': ['VA1', 'BA', 'GA', 'VA', 'VA2'],
                          'ban': False,
                          'baned': False,
                          'blocked': 'N',
                          'createDate': '1749105364000',
                          'currencyId': 'USDT',
                          'executedQuantity': '0',
                          'fee': '',
                          'finishNum': 70,
                          'frozenQuantity': '0',
                          'id': '1930513933409165312',
                          'isOnline': True,
                          'itemType': 'ORIGIN',
                          'lastLogoutTime': '1756101907',
                          'lastQuantity': '1',
                          'makerContact': False,
                          'maxAmount': '422017.50',
                          'minAmount': '20000.00',
                          'nickName': 'TowerOfPower',
                          'orderNum': 71,
                          'paymentPeriod': 15,
                          'payments': ['64', '612', '613', '614'],
                          'premium': '111.8',
                          'price': '422017.50',
                          'priceType': 1,
                          'quantity': '1',
                          'recentExecuteRate': 100,
                          'recentOrderNum': 649,
                          'recommend': False,
                          'recommendTag': '',
                          'remark': 'ОТКРЫВАЯ ОРДЕР ВЫ СОГЛАШАЕТЕСЬ С МОИМИ '
                                 'УСЛОВЯМИ\n'
                                 '\n'
                                 'Оплата по СБП\n'
                                 'Оплата принимается только с банков, '
                                 'указанных в сделке\n'
                                 'После оплаты принимаю только чек в формате '
                                 'PDF\n'
                                 'Могу запросить разделение платежа\n'
                                 'Принимаю на карту доверенного лица\n'
                                 'При необходимости могу запросить доп. '
                                 'подтверждения платежа\n'
                                 '\n'
                                 'При переводе не туда - средства не '
                                 'возвращаются\n'
                                 'Третье лицо - фото карты или видео из '
                                 'личного кабинета НА ФОНЕ ордера\n'
                                 'Не принимаю переводы с ИП и пополнения с '
                                 'банкоматов',
                          'side': 1,
                          'status': 10,
                          'symbolInfo': {'buyAd': None,
                                         'buyFeeRate': '',
                                         'currency': {'currencyId': 'RUB',
                                                      'exchangeId': '0',
                                                      'id': '7',
                                                      'orgId': '9001',
                                                      'scale': 2},
                                         'currencyId': 'RUB',
                                         'currencyLowerMaxQuote': '500',
                                         'currencyMaxQuote': '3500000',
                                         'currencyMinQuote': '500',
                                         'exchangeId': '301',
                                         'id': '36',
                                         'itemDownRange': '80',
                                         'itemSideLimit': 3,
                                         'itemUpRange': '120',
                                         'k$1=<SECRET_API_KEY>': '0',
                                         'lowerLimitAlarm': 90,
                                         'orderAutoCancelMinute': 15,
                                         'orderFinishMinute': 10,
                                         'orgId': '9001',
                                         'sellAd': None,
                                         'sellFeeRate': '',
                                         'status': 1,
                                         'token': {'exchangeId': '0',
                                                   'id': '3',
                                                   'orgId': '9001',
                                                   'scale': 8,
                                                   'sequence': 0,
                                                   'tokenId': 'ETH'},
                                         'tokenId': 'ETH',
                                         'tokenMaxQuote': '30',
                                         'tokenMinQuote': '0.001',
                                         'tradeSide': 9,
                                         'upperLimitAlarm': 110},
                          'tokenId': 'BTC',
                          'tokenName': '',
                          'tradingPreferenceSet': {'completeRateDay30': '0',
                                                   'hasCompleteRateDay30': 0,
                                                   'hasNationalLimit': 0,
                                                   'hasOrderFinishNumberDay30': 0,
                                                   'hasRegisterTime': 1,
                                                   'hasSingleUserOrderLimit': 0,
                                                   'hasUnPostAd': 0,
                                                   'isEmail': 0,
                                                   'isKyc': 1,
                                                   'isMobile': 0,
                                                   'nationalLimit': '',
                                                   'orderFinishNumberDay30': 0,
                                                   'registerTimeThreshold': 30,
                                                   'singleUserOrderLimit': 0},
                          'userId': '25944050',
                          'userMaskId': 's17572d8249664ffbb8f971a9f0be5ac7',
                          'userType': 'PERSONAL',
                          'verificationOrderAmount': '0',
                          'verificationOrderLabels': [],
                          'verificationOrderSwitch': False,
                          'version': 0},
                         {'accountId': '65484805',
                          'authStatus': 1,
                          'authTag': ['VA1', 'GA', 'VA'],
                          'ban': False,
                          'baned': False,
                          'blocked': 'N',
                          'createDate': '1748435831000',
                          'currencyId': 'RUB',
                          'executedQuantity': '0',
                          'fee': '',
                          'finishNum': 255,
                          'frozenQuantity': '0',
                          'id': '1927705706706849792',
                          'isOnline': True,
                          'itemType': 'ORIGIN',
                          'lastLogoutTime': '1756098560',
                          'lastQuantity': '0.50651628',
                          'makerContact': True,
                          'maxAmount': '200000.00',
                          'minAmount': '20000.00',
                          'nickName': 'monty.mcqueen',
                          'orderNum': 258,
                          'paymentPeriod': 30,
                          'payments': ['581', '582', '382'],
                          'premium': '111.8',
                          'price': '422017.50',
                          'priceType': 1,
                          'quantity': '0.50651628',
                          'recentExecuteRate': 97,
                          'recentOrderNum': 1398,
                          'recommend': False,
                          'recommendTag': '',
                          'remark': 'Помогу новичкам разобраться!\n'
                                 ' Принимаю от 1-Х лиц, от 3-Х лиц только с '
                                 'ФОТО на фоне сделки \n'
                                 ' Работаю по СБП, по номеру телефона, с '
                                 'любыми банками \n'
                                 ' Работаю в порядке очереди ',
                          'side': 1,
                          'status': 10,
                          'symbolInfo': {'buyAd': None,
                                         'buyFeeRate': '',
                                         'currency': {'currencyId': 'RUB',
                                                      'exchangeId': '0',
                                                      'id': '7',
                                                      'orgId': '9001',
                                                      'scale': 2},
                                         'currencyId': 'RUB',
                                         'currencyLowerMaxQuote': '500',
                                         'currencyMaxQuote': '3500000',
                                         'currencyMinQuote': '500',
                                         'exchangeId': '301',
                                         'id': '36',
                                         'itemDownRange': '80',
                                         'itemSideLimit': 3,
                                         'itemUpRange': '120',
                                         'k$1=<SECRET_API_KEY>': '0',
                                         'lowerLimitAlarm': 90,
                                         'orderAutoCancelMinute': 15,
                                         'orderFinishMinute': 10,
                                         'orgId': '9001',
                                         'sellAd': None,
                                         'sellFeeRate': '',
                                         'status': 1,
                                         'token': {'exchangeId': '0',
                                                   'id': '3',
                                                   'orgId': '9001',
                                                   'scale': 8,
                                                   'sequence': 0,
                                                   'tokenId': 'ETH'},
                                         'tokenId': 'ETH',
                                         'tokenMaxQuote': '30',
                                         'tokenMinQuote': '0.001',
                                         'tradeSide': 9,
                                         'upperLimitAlarm': 110},
                          'tokenId': 'ETH',
                          'tokenName': '',
                          'tradingPreferenceSet': {'completeRateDay30': '',
                                                   'hasCompleteRateDay30': 0,
                                                   'hasNationalLimit': 0,
                                                   'hasOrderFinishNumberDay30': 0,
                                                   'hasRegisterTime': 0,
                                                   'hasSingleUserOrderLimit': 0,
                                                   'hasUnPostAd': 0,
                                                   'isEmail': 0,
                                                   'isKyc': 1,
                                                   'isMobile': 0,
                                                   'nationalLimit': '',
                                                   'orderFinishNumberDay30': 0,
                                                   'registerTimeThreshold': 0,
                                                   'singleUserOrderLimit': 0},
                          'userId': '65484804',
                          'userMaskId': 'se9442e769a3543698a2c38665d9760ed',
                          'userType': 'PERSONAL',
                          'verificationOrderAmount': '0',
                          'verificationOrderLabels': [],
                          'verificationOrderSwitch': False,
                          'version': 0},
                         {'accountId': '31010708',
                          'authStatus': 1,
                          'authTag': ['VA1', 'BA', 'GA', 'VA', 'VA2', 'VA3'],
                          'ban': False,
                          'baned': False,
                          'blocked': 'N',
                          'createDate': '1698177851000',
                          'currencyId': 'RUB',
                          'executedQuantity': '0.3474252',
                          'fee': '',
                          'finishNum': 204,
                          'frozenQuantity': '0',
                          'id': '1716908461627637760',
                          'isOnline': True,
                          'itemType': 'ORIGIN',
                          'lastLogoutTime': '1755977099',
                          'lastQuantity': '0.32102943',
                          'makerContact': True,
                          'maxAmount': '136327.22',
                          'minAmount': '20000.00',
                          'nickName': 'Wins!',
                          'orderNum': 204,
                          'paymentPeriod': 30,
                          'payments': ['581', '582', '583', '383'],
                          'premium': '0',
                          'price': '424656.46',
                          'priceType': 0,
                          'quantity': '0.66845463',
                          'recentExecuteRate': 99,
                          'recentOrderNum': 1556,
                          'recommend': False,
                          'recommendTag': '',
                          'remark': 'Доброго времени суток,\n'
                                 'Принимаю со всех банков РФ работаю по Сбп, '
                                 'Реквизиты выдаю в чате\n'
                                 'Не принимаю от 3 лиц\n'
                                 'Принимаю на карту доверенного лица\n'
                                 'При долгой транзакции или при подозрении '
                                 'на мошенничество могу запросить фото карты '
                                 'на фоне сделки или верну перевод обратно '
                                 'отправителю',
                          'side': 1,
                          'status': 10,
                          'symbolInfo': {'buyAd': None,
                                         'buyFeeRate': '',
                                         'currency': {'currencyId': 'RUB',
                                                      'exchangeId': '0',
                                                      'id': '7',
                                                      'orgId': '9001',
                                                      'scale': 2},
                                         'currencyId': 'RUB',
                                         'currencyLowerMaxQuote': '500',
                                         'currencyMaxQuote': '3500000',
                                         'currencyMinQuote': '500',
                                         'exchangeId': '301',
                                         'id': '36',
                                         'itemDownRange': '80',
                                         'itemSideLimit': 3,
                                         'itemUpRange': '120',
                                         'k$1=<SECRET_API_KEY>': '0',
                                         'lowerLimitAlarm': 90,
                                         'orderAutoCancelMinute': 15,
                                         'orderFinishMinute': 10,
                                         'orgId': '9001',
                                         'sellAd': None,
                                         'sellFeeRate': '',
                                         'status': 1,
                                         'token': {'exchangeId': '0',
                                                   'id': '3',
                                                   'orgId': '9001',
                                                   'scale': 8,
                                                   'sequence': 0,
                                                   'tokenId': 'ETH'},
                                         'tokenId': 'ETH',
                                         'tokenMaxQuote': '30',
                                         'tokenMinQuote': '0.001',
                                         'tradeSide': 9,
                                         'upperLimitAlarm': 110},
                          'tokenId': 'ETH',
                          'tokenName': '',
                          'tradingPreferenceSet': {'completeRateDay30': '85',
                                                   'hasCompleteRateDay30': 0,
                                                   'hasNationalLimit': 0,
                                                   'hasOrderFinishNumberDay30': 0,
                                                   'hasRegisterTime': 1,
                                                   'hasSingleUserOrderLimit': 0,
                                                   'hasUnPostAd': 0,
                                                   'isEmail': 0,
                                                   'isKyc': 1,
                                                   'isMobile': 0,
                                                   'nationalLimit': '',
                                                   'orderFinishNumberDay30': 0,
                                                   'registerTimeThreshold': 30,
                                                   'singleUserOrderLimit': 0},
                          'userId': '31010707',
                          'userMaskId': 's3577fdaee2c04706a9308ccfc0558c53',
                          'userType': 'PERSONAL',
                          'verificationOrderAmount': '0',
                          'verificationOrderLabels': [],
                          'verificationOrderSwitch': False,
                          'version': 0}]},
    'ret_code': 0,
    'ret_msg': 'SUCCESS',
    'time_now': '1756102966.162200'
}